Models/Character.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KingdomOfRelationships.Models
{
    public class Character
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int CharacterId { get; set; }

        [StringLength(255)]
        public string Name { get; set; }
    }
}

Models/CharacterRelationships.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace KingdomOfRelationships.Models
{
    public class CharacterRelationships
    {
        public int CharacterRelationshipsId { get; set; }

        [ForeignKey("ParentCharacterId")]
        public Character ParentCharacter { get; set; }

        [ForeignKey("RelationshipId")]
        public Relationship Relationship { get; set; }

        [ForeignKey("ChildCharacterId")]
        public Character ChildCharacter { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace KingdomOfRelationships.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Relationship.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KingdomOfRelationships.Models
{
    public class Relationship
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int RelationshipId { get; set; }
        
        [StringLength(255)]
        public string Description { get; set; }
    }
}

Models/TempRepoContext.cs
using Microsoft.EntityFrameworkCore;
namespace KingdomOfRelationships.Models
{
    public class TempRepoContext : DbContext
    {
        public DbSet<Character> Characters { get; set; }
        public DbSet<Relationship> Relationships { get; set; }
        public DbSet<CharacterRelationships> CharacterRelationship { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=localhost\SQLEXPRESS01;Database=master;Trusted_Connection=True;");
        }
    }
}

ViewModels/CharacterRelationshipsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using KingdomOfRelationships.Models;

namespace KingdomOfRelationships
{
    public class CharacterRelationshipsViewModel
    {
        public List<Character> Characters { get; set; }
        public List<Relationship> Relationships { get; set; }
        public int SelectedParentCharacter { get; set; }
        public int SelectedChildCharacter { get; set; }
        public int SelectedRelationship { get; set; }
    }
}

ViewModels/CharacterViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using KingdomOfRelationships.Models;

namespace KingdomOfRelationships
{
    public class CharacterViewModel
    {
        public Character Character { get; set; }
        public List<Character> RelatedCharacters { get; set; }
    }
}

Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KingdomOfRelationships.Models;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using KingdomOfRelationships.Helpers;

namespace KingdomOfRelationships.Controllers
{
    public class CharacterController : Controller
    {
        public ActionResult Index(int id = 1)
        {
            using (var context = new TempRepoContext())
            {
                var vm = new CharacterViewModel();
                vm.Character = context.Characters.FirstOrDefault(x => x.CharacterId == id);
                // Get parents
                vm.RelatedCharacters = context.CharacterRelationship
                                    .Where(x => x.ParentCharacter.CharacterId == id)
                                    .Select(x => new Character()
                                    {
                                        CharacterId = x.ChildCharacter.CharacterId,
                                        Name = x.ChildCharacter.Name
                                    }).ToList();
                // Get children
                vm.RelatedCharacters.AddRange(context.CharacterRelationship
                                    .Where(x => x.ChildCharacter.CharacterId == id)
                                    .Select(x => new Character()
                                    {
                                        CharacterId = x.ParentCharacter.CharacterId,
                                        Name = x.ParentCharacter.Name
                                    }).ToList());
                // strip duplicates
                vm.RelatedCharacters = vm.RelatedCharacters.Distinct(new DistinctCharacterComparer()).ToList();
                return View(vm);
            }
        }
    }
}

Controllers/CharacterRelationshipsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KingdomOfRelationships.Models;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace KingdomOfRelationships.Controllers
{
    public class CharacterRelationshipsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using (var context = new TempRepoContext())
            {
                var model = await context.CharacterRelationship
                .Include(CharacterRelationships => CharacterRelationships.ParentCharacter)
                .Include(CharacterRelationships => CharacterRelationships.ChildCharacter)
                .Include(CharacterRelationships => CharacterRelationships.Relationship)
                .AsNoTracking()
                .ToListAsync();
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            using (var context = new TempRepoContext())
            {
                var vm = new CharacterRelationshipsViewModel();
                vm.Characters = context.Characters.AsNoTracking().OrderBy(c => c.Name).ToList();
                vm.Relationships = context.Relationships.AsNoTracking().OrderBy(r => r.Description).ToList();
                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult Create(CharacterRelationshipsViewModel viewModel)
        {
            using (var context = new TempRepoContext())
            {
                context.CharacterRelationship.Add(new CharacterRelationships()
                {
                    ChildCharacter = context.Characters.SingleOrDefault(x => x.CharacterId == viewModel.SelectedChildCharacter),
                    ParentCharacter = context.Characters.SingleOrDefault(x => x.CharacterId == viewModel.SelectedParentCharacter),
                    Relationship = context.Relationships.SingleOrDefault(x => x.RelationshipId == viewModel.SelectedRelationship),
                });
                context.SaveChanges();
            }
            return RedirectToAction("Index", viewModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using KingdomOfRelationships.Models;

namespace KingdomOfRelationships.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Character/Index.cshtml
@model CharacterViewModel
@{
    var characterNameDisplay = @Model.Character.Name;
    var characterNameForImageFile = characterNameDisplay.Replace(" ", "_");
    ViewBag.Title = characterNameDisplay;
}

<div class="row">
    <div class="column">
        <h2>@ViewBag.Title</h2>
        <p>
            @{
                var img = "/images/" + characterNameForImageFile + ".png";
                <img src="@Url.Content(img)" alt=@characterNameDisplay>
            }
        </p>
    </div>

    <div class="column">
        <p>
            <h2>Related to</h2>
            <ul>
                @foreach(var relation in Model.RelatedCharacters)
                {
                    <ul>
                        <li>
                            @Html.ActionLink(@relation.Name, "Index", "Character", new { @id = relation.CharacterId }, null)
                        </li>
                    </ul>
                }
            </ul>
        </p>
    </div>
</div>
    

Views/CharacterRelationships/Create.cshtml
@model CharacterRelationshipsViewModel
@{
    ViewBag.Title = "New character relationships";
}
<h1>@ViewBag.Title</h1>

<form asp-controller="CharacterRelationships" asp-action="Create" method="post">
<select asp-for="SelectedParentCharacter" asp-items="@(new SelectList(Model.Characters,"CharacterId","Name"))"></select> 
<select asp-for="SelectedRelationship" asp-items="@(new SelectList(Model.Relationships,"RelationshipId","Description"))"></select> 
<select asp-for="SelectedChildCharacter" asp-items="@(new SelectList(Model.Characters,"CharacterId","Name"))"></select> 

<br /><button type="submit">Create relationship</button>
</form>

Views/CharacterRelationships/Index.cshtml
@model IEnumerable<CharacterRelationships>
    @{
        ViewBag.Title = "Character Relationships";
        <h1>@ViewBag.Title</h1>
        <ul>
            @foreach (var characterRelationship in Model)
            {
                <li>
                    @characterRelationship.ParentCharacter.Name is @characterRelationship.Relationship.Description with @characterRelationship.ChildCharacter.Name
                </li>
            }
        </ul>
    }

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KingdomOfRelationships</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KingdomOfRelationships</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CharacterRelationships" asp-action="Index">View Character Relationships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CharacterRelationships" asp-action="Create">Create Character Relationships</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Index">View Character page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - KingdomOfRelationships - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>